spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mydb1?characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai&rewriteBatchedStatements=true
    username: root
    password: root
  web:
    resources:
      static-locations: classpath:/static,file:./files,file:./temp
  mvc:
  servlet:
    multipart:
      max-file-size: 3MB        # 设置单个文件最大大小为10MB
      max-request-size: 30MB    # 设置多个文件大小为100MB

server:
  additionalPorts: 80

upload:
  passwd: 123456

bottle:
  max:
    pickup: 5

auth:
  url: http://localhost:20049
  pwd: 123456
